import { describe, expect, it, vi } from 'vitest';
import { aggregateHistorical, buildSafetyComment, composeSafetyReport, distanceKm, periodWindow } from './safety-report-service';
import { calculateRisk } from '../lib/risk/risk-engine';
vi.mock('../lib/supabase/client',()=>({supabase:null}));
const now=new Date('2026-08-15T06:00:00.000Z');
const fixture={sessions:[{id:'done',device_id:'d1',started_at:'2026-08-14T23:00:00Z',ended_at:'2026-08-15T02:30:00Z',status:'completed' as const}],locations:[{device_id:'d1',latitude:33,longitude:126,measured_at:'2026-08-15T00:00:00Z',activity_status:'diving'},{device_id:'d1',latitude:33,longitude:126.01,measured_at:'2026-08-15T01:00:00Z',activity_status:'moving'}],risks:[{score:10,level:'safe' as const,calculated_at:'2026-08-15T00:00:00Z'},{score:50,level:'warning' as const,calculated_at:'2026-08-15T01:00:00Z',factors:[{code:'high_wave',category:'weather',score:25,description:'최대 파고 1.7m'}]}],alerts:[{id:'1',title:'위험구역 접근',message:'경계 접근',type:'danger_zone',severity:'warning' as const,status:'open' as const,occurred_at:'2026-08-15T01:20:00Z'}],device:{status:'online' as const,battery_level:72,last_communicated_at:'2026-08-15T05:58:00Z'}};
describe('웹/앱 현재 위험 parity',()=>{
 it('DB 최신 risk_scores의 점수와 단계를 공공데이터 재계산보다 우선한다',()=>{const report=composeSafetyReport('daily',{...fixture,currentRisk:fixture.risks[1],currentLocation:fixture.locations[1]}, {windSpeedMps:11},now);expect(report.current).toMatchObject({score:50,level:'warning',levelLabel:'경고'});expect(report.current.factors).toEqual(expect.arrayContaining([expect.objectContaining({code:'high_wave',score:25}),expect.objectContaining({code:'strong_wind',score:25})]));});
 it('work_session이 없어도 최신 위치/장치/위험점수로 일간 리포트를 만든다',()=>{const report=composeSafetyReport('daily',{...fixture,sessions:[],currentRisk:fixture.risks[1],currentLocation:fixture.locations[1]}, {},now);expect(report.hasData).toBe(true);expect(report.currentActivity).toMatchObject({activityStatus:'moving',battery:'72%',connectionStatus:'연결됨'});});
 it('웹과 동일한 규칙 임계값과 가산점을 쓴다',()=>{expect(calculateRisk({assessedAt:now.toISOString(),windSpeedMps:10,waveHeightM:2})).toMatchObject({score:80,level:'danger',factors:[{code:'strong_wind',score:25},{code:'high_wave',score:40},{code:'compound_weather',score:15}]});});
});
describe('기간 집계',()=>{it('KST 최근 7일/30일 경계를 유지한다',()=>{expect(periodWindow('weekly',now).from).toBe('2026-08-08T15:00:00.000Z');expect(periodWindow('monthly',now).from).toBe('2026-07-16T15:00:00.000Z');});it('주간/월간에서만 사용할 실제 지표를 집계한다',()=>{const historical=aggregateHistorical('weekly',fixture);expect(historical.activity).toMatchObject({workDuration:'3시간 30분',sessionCount:'1건',highestRisk:'50점',averageRisk:'30점',alertCount:'1건'});expect(historical.activity.travelDistance).toBe(`${distanceKm(fixture.locations[0]!,fixture.locations[1]!).toFixed(1)} km`);});});

describe('점수 기반 표시 단계와 상세 코멘트',()=>{
  it.each([[0,'safe'],[18,'safe'],[30,'caution'],[55,'warning'],[85,'danger'],[100,'danger']] as const)('%i점은 %s 단계로 표시한다',(score,level)=>{const report=composeSafetyReport('daily',{sessions:[],locations:[],risks:[],alerts:[],currentRisk:{score,level:'danger'}},{},now);expect(report.current.level).toBe(level);expect(report.comment.headline).toContain(`${score}점`);});
  it('긴급 버튼을 최우선으로 설명하고 안정적이라고 표현하지 않는다',()=>{const comment=buildSafetyComment({score:85,factors:[],location:{latitude:33,longitude:126,measured_at:now.toISOString(),emergency_button:true},device:{status:'online',battery_level:90,last_communicated_at:now.toISOString()},alerts:[]});expect(comment.details[0]).toContain('긴급 버튼');expect(comment.details.join(' ')).not.toContain('안정');expect(comment.details).toHaveLength(2);});
  it('통신두절을 명시한다',()=>{const comment=buildSafetyComment({score:30,factors:[{code:'communication_lost',category:'device',score:20,description:'장치 통신 끊김'}],location:null,device:{status:'offline',battery_level:50,last_communicated_at:null},alerts:[]});expect(comment.details.join(' ')).toContain('통신이 끊긴');});
  it('강풍과 높은 파고의 실제 수치만 설명한다',()=>{const comment=buildSafetyComment({score:55,factors:[{code:'strong_wind',category:'weather',score:25,description:'최대 풍속 11.0m/s'},{code:'high_wave',category:'weather',score:40,description:'최대 파고 2.1m'}],location:null,device:null,alerts:[],environment:{windSpeedMps:11,waveHeightM:2.1}});expect(comment.details.join(' ')).toContain('풍속 11.0m/s');expect(comment.details.join(' ')).toContain('파고 2.1m');});
  it('완전 안전 상태를 설명한다',()=>{const comment=buildSafetyComment({score:0,factors:[],location:{latitude:33,longitude:126,measured_at:now.toISOString()},device:{status:'online',battery_level:88,last_communicated_at:now.toISOString()},alerts:[]});expect(comment.details.join(' ')).toContain('뚜렷한 위험요인은 확인되지 않았습니다');});
  it('공공데이터 no_data와 historical 부재에서 가짜 수치를 만들지 않는다',()=>{const comment=buildSafetyComment({score:18,factors:[],location:null,device:null,alerts:[],environment:{windSpeedMps:null,waveHeightM:null},historical:null});expect(comment.details.join(' ')).toContain('데이터가 아직 충분하지 않아');expect(comment.details.join(' ')).not.toMatch(/m\/s|파고|평균 위험도/);});
});
