import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ShieldCheck } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/theme';
import { isSupabaseConfigured } from '@/lib/supabase/client';
import { useAuthStore } from '@/stores/auth-store';

export default function LoginScreen() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const signIn = useAuthStore((s) => s.signIn); const loading = useAuthStore((s) => s.loading); const error = useAuthStore((s) => s.error);
  const login = async () => { if (!email.trim() || !password) return Alert.alert('입력 필요', '이메일과 비밀번호를 입력해 주세요.'); await signIn(email, password); };
  return <SafeAreaView style={styles.safe}><View style={styles.wrap}><View style={styles.logo}><ShieldCheck size={34} color="white" /></View><Text style={styles.title}>HAEON SAFE</Text><Text style={styles.sub}>안전한 바다 작업을 위한 모바일 파트너</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="이메일" style={styles.input} editable={!loading} /><TextInput secureTextEntry autoComplete="password" value={password} onChangeText={setPassword} placeholder="비밀번호" style={styles.input} editable={!loading} onSubmitEditing={() => void login()} />{error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<Pressable disabled={loading || !isSupabaseConfigured} onPress={() => void login()} style={[styles.button, (loading || !isSupabaseConfigured) && styles.disabled]}><Text style={styles.buttonText}>{loading ? '로그인 중...' : '로그인'}</Text></Pressable>{!isSupabaseConfigured && <Text style={styles.notice}>앱 환경변수에 Supabase URL과 Publishable Key가 필요합니다.</Text>}</View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background, justifyContent: 'center' }, wrap: { padding: 28, alignItems: 'center' }, logo: { width: 64, height: 64, borderRadius: 20, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, title: { fontSize: 22, fontWeight: '900', color: colors.text }, sub: { fontSize: 12, color: colors.muted, marginTop: 6, marginBottom: 28 }, input: { width: '100%', height: 48, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: 'white', borderRadius: 12, marginBottom: 10, fontSize: 13 }, button: { width: '100%', height: 48, backgroundColor: colors.primary, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 4 }, disabled: { opacity: 0.45 }, buttonText: { color: 'white', fontWeight: '900', fontSize: 13 }, notice: { fontSize: 10, lineHeight: 15, color: colors.muted, textAlign: 'center', marginTop: 14 }, error: { width: '100%', color: '#B42318', fontSize: 11, marginBottom: 8 } });
