import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { ShieldCheck } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/theme';
import { isSupabaseConfigured, supabase } from '@/lib/supabase/client';
export default function LoginScreen() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const login = async () => { if (!supabase) return Alert.alert('환경변수 필요', 'Supabase URL과 Publishable Key를 설정해 주세요.'); setLoading(true); const { error } = await supabase.auth.signInWithPassword({ email, password }); setLoading(false); if (error) Alert.alert('로그인 실패', error.message); else router.replace('/'); }; return <SafeAreaView style={styles.safe}><View style={styles.wrap}><View style={styles.logo}><ShieldCheck size={34} color="white" /></View><Text style={styles.title}>HAEON SAFE</Text><Text style={styles.sub}>안전한 바다 작업을 위한 모바일 파트너</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="이메일" style={styles.input} /><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="비밀번호" style={styles.input} /><Pressable disabled={loading || !isSupabaseConfigured} onPress={login} style={[styles.button, !isSupabaseConfigured && styles.disabled]}><Text style={styles.buttonText}>{loading ? '로그인 중...' : '로그인'}</Text></Pressable>{!isSupabaseConfigured && <Text style={styles.notice}>현재 데모 모드입니다. .env 환경변수를 설정하면 로그인을 사용할 수 있어요.</Text>}<Pressable onPress={() => router.replace('/')}><Text style={styles.skip}>앱 먼저 둘러보기</Text></Pressable></View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background, justifyContent: 'center' }, wrap: { padding: 28, alignItems: 'center' }, logo: { width: 64, height: 64, borderRadius: 20, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, title: { fontSize: 22, fontWeight: '900', color: colors.text }, sub: { fontSize: 12, color: colors.muted, marginTop: 6, marginBottom: 28 }, input: { width: '100%', height: 48, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: 'white', borderRadius: 12, marginBottom: 10, fontSize: 13 }, button: { width: '100%', height: 48, backgroundColor: colors.primary, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 4 }, disabled: { opacity: 0.45 }, buttonText: { color: 'white', fontWeight: '900', fontSize: 13 }, notice: { fontSize: 10, lineHeight: 15, color: colors.muted, textAlign: 'center', marginTop: 14 }, skip: { fontSize: 11, fontWeight: '800', color: colors.primary, marginTop: 18 } });
