import type { ComponentType } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { BellRing, ChevronLeft, ChevronRight, Clock3, HeartHandshake, Moon, Phone, ShieldAlert, UserRound, UsersRound, type LucideProps } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/theme';
import { IconCircle } from '@/components/ui';
import { useAppSettingsStore } from '@/stores/app-settings-store';
type RowProps = { icon: ComponentType<LucideProps>; title: string; subtitle: string; value?: string; toggle?: boolean; enabled?: boolean; onToggle?: (value: boolean) => void };
function SettingRow({ icon: Icon, title, subtitle, value, toggle, enabled, onToggle }: RowProps) { return <View style={styles.row}><View style={styles.left}><IconCircle><Icon size={16} color={colors.primary} /></IconCircle><View><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSub}>{subtitle}</Text></View></View>{toggle ? <Switch value={enabled} onValueChange={onToggle} trackColor={{ false: '#D8DCE4', true: colors.primary }} thumbColor="white" /> : <View style={styles.value}><Text style={styles.valueText}>{value}</Text><ChevronRight size={14} color={colors.muted} /></View>}</View>; }
export default function SettingsScreen() { const settings = useAppSettingsStore(); return <SafeAreaView style={styles.safe} edges={['top', 'bottom']}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><ChevronLeft size={22} color={colors.text} /></Pressable><Text style={styles.headerTitle}>설정</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.section}>사용자 정보</Text><View style={styles.profile}><View style={styles.avatar}><UserRound size={22} color={colors.primary} /></View><View style={styles.profileCopy}><Text style={styles.profileName}>홍길동 (68세)</Text><Text style={styles.profileSub}>제주 해녀 안전관리 사용자</Text></View><Pressable style={styles.edit}><Text style={styles.editText}>정보 수정</Text></Pressable></View><Text style={styles.section}>개인 맞춤 안전 설정</Text><View style={styles.group}><SettingRow icon={ShieldAlert} title="위험도 민감도" subtitle="위험 알림 기준 설정" value={settings.sensitivity} /><SettingRow icon={BellRing} title="위험 알림 설정" subtitle="푸시·긴급 알림 관리" toggle enabled={settings.riskNotifications} onToggle={settings.setRiskNotifications} /><SettingRow icon={Clock3} title="활동 시간 설정" subtitle={`${settings.activityStart} ~ ${settings.activityEnd}`} /><SettingRow icon={Moon} title="야간 알림 모드" subtitle="야간 위험 탐지 강화" toggle enabled={settings.nightMode} onToggle={settings.setNightMode} /></View><Text style={styles.section}>보호자 및 공동 대응</Text><View style={styles.group}><SettingRow icon={HeartHandshake} title="보호자 관리" subtitle="2명 등록됨" /><SettingRow icon={Phone} title="긴급 연락망" subtitle="가족·어촌계·복지사" /><SettingRow icon={UsersRound} title="공동 대응 기관" subtitle="3곳 연계됨" /></View></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.surface }, header: { height: 56, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10 }, back: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, headerTitle: { fontSize: 16, fontWeight: '900', color: colors.text }, content: { backgroundColor: colors.background, paddingHorizontal: 16, paddingBottom: 30 }, section: { fontSize: 15, fontWeight: '900', color: colors.text, marginTop: 18, marginBottom: 10 }, profile: { backgroundColor: 'white', borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#EEE8FF', alignItems: 'center', justifyContent: 'center' }, profileCopy: { flex: 1 }, profileName: { fontSize: 12, fontWeight: '800', color: colors.text }, profileSub: { fontSize: 9, color: colors.muted, marginTop: 3 }, edit: { borderWidth: 1, borderColor: '#D8DCE4', borderRadius: 10, paddingVertical: 7, paddingHorizontal: 10 }, editText: { color: '#6B7280', fontSize: 9, fontWeight: '800' }, group: { backgroundColor: 'white', borderWidth: 1, borderColor: colors.line, borderRadius: 15, overflow: 'hidden' }, row: { minHeight: 57, padding: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#DEE1E7', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, left: { flexDirection: 'row', alignItems: 'center', gap: 9 }, rowTitle: { fontSize: 11, fontWeight: '800', color: colors.text }, rowSub: { fontSize: 9, color: colors.muted, marginTop: 2 }, value: { flexDirection: 'row', alignItems: 'center' }, valueText: { color: colors.muted, fontSize: 10 } });
