import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LocateFixed, Search, X } from 'lucide-react-native';
import { KakaoMapView } from '@/components/kakao-map-view';
import { colors } from '@/constants/theme';
import { markersForLayer, sampleMarkers, sampleRiskZones, searchMarkers } from '@/data/map-data';
import { useDeviceLocation } from '@/hooks/use-device-location';
import { useMarineForecast, useOceanBuoy, useShortTermForecast, useTidalCurrent, useTidalObservation, useTideForecast, useWaveObservation, useWeatherAlert } from '@/hooks/use-public-data';
import type { EnvironmentLayer, MapMarker } from '@/types/domain';
import type { PublicDataResult } from '@/types/public-data';
const filters: { label: string; value: EnvironmentLayer }[] = [{ label: '통합', value: 'all' }, { label: '해녀', value: 'haenyeo' }, { label: '태왁', value: 'taewak' }, { label: '위험구역', value: 'danger-zone' }, { label: '풍향·풍속', value: 'wind' }, { label: '수온', value: 'water-temperature' }, { label: '유향·유속', value: 'current' }, { label: '기온', value: 'air-temperature' }, { label: '파고·파주기', value: 'wave' }, { label: '조석', value: 'tide' }];
const val = (r: PublicDataResult | undefined, ...keys: string[]) => { if (r?.status !== 'success') return null; for (const k of keys) { const v = r.latest?.values[k] ?? r.latest?.raw[k]; if (v !== undefined && v !== null && v !== '') return v; } return null; };
const forecastValue = (r: PublicDataResult | undefined, category: string) => r?.status === 'success' ? r.data.items.filter((item) => item.values.category === category).at(-1)?.values.value ?? null : null;
const show = (v: unknown, unit: string) => v === null || v === undefined ? '데이터 없음' : `${v}${unit}`;
export default function HomeScreen() {
  const [active, setActive] = useState<EnvironmentLayer>('all'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<MapMarker>();
  const location = useDeviceLocation();
  const alert = useWeatherAlert(); const forecast = useShortTermForecast(); const wave = useWaveObservation(); const current = useTidalCurrent();
  const tidal = useTidalObservation(); const tides = useTideForecast(); const buoy = useOceanBuoy(); const marine = useMarineForecast();
  const results = useMemo(() => searchMarkers(sampleMarkers, query), [query]);
  const visibleMarkers = markersForLayer(sampleMarkers, active);
  const overlay = useMemo(() => {
    if (active === 'wind') return `풍속 ${show(val(buoy.data, 'windSpeed', 'wspd') ?? forecastValue(forecast.data, 'WSD'), ' m/s')}`;
    if (active === 'water-temperature') return `수온 ${show(val(tidal.data, 'waterTemperature', 'wtem') ?? val(buoy.data, 'waterTemperature', 'wtem'), ' ℃')}`;
    if (active === 'current') return current.data?.status === 'no_data' ? '조류 · 데이터 없음 (정상 응답)' : `유향 ${show(val(current.data, 'currentDirection'), '°')} · 유속 ${show(val(current.data, 'currentSpeed'), ' cm/s')}`;
    if (active === 'air-temperature') return `기온 ${show(val(buoy.data, 'airTemperature', 'artmp') ?? forecastValue(forecast.data, 'TMP'), ' ℃')}`;
    if (active === 'wave') return `파고 ${show(val(wave.data, 'waveHeight') ?? val(buoy.data, 'waveHeight'), ' m')} · 파주기 ${show(val(wave.data, 'wavePeriod'), ' s')}`;
    if (active === 'tide') return `현재 조위 ${show(val(tidal.data, 'tideLevel'), ' cm')} · 예측 ${tides.data?.status === 'success' ? `${tides.data.data.items.length}건` : '데이터 없음'}`;
    if (active === 'danger-zone') return `기상특보 ${show(val(alert.data, 'title'), '')}`;
    return null;
  }, [active, alert.data, buoy.data, current.data, forecast.data, tidal.data, tides.data, wave.data]);
  // marine-forecast까지 화면 query lifecycle에 포함하며 상세 텍스트는 물때 상세에서 표시한다.
  void marine.data;
  return <View style={styles.container}><KakaoMapView markers={visibleMarkers} activeLayer={active} camera={location.camera} riskZones={sampleRiskZones} onMarkerPress={setSelected} />
    <View style={styles.search}><Search size={16} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} style={styles.input} placeholder="해녀 이름, 태왁 ID, 지역을 검색하세요" placeholderTextColor="#9DA3AF" />{query ? <Pressable onPress={() => setQuery('')}><X size={16} color={colors.muted} /></Pressable> : null}</View>
    {results.length > 0 && <View style={styles.results}>{results.map((marker) => <Pressable key={marker.id} style={styles.result} onPress={() => { setSelected(marker); location.setCamera({ latitude: marker.latitude, longitude: marker.longitude, zoom: 4 }); setQuery(''); }}><Text style={styles.resultTitle}>{marker.label}</Text><Text style={styles.resultMeta}>{marker.userCode ?? marker.deviceCode} · {marker.region} · 샘플</Text></Pressable>)}</View>}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.filters} contentContainerStyle={styles.filterContent}>{filters.map((filter) => <Pressable key={filter.value} onPress={() => setActive(filter.value)} style={[styles.chip, active === filter.value && styles.activeChip]}><Text style={[styles.chipText, active === filter.value && styles.activeChipText]}>{filter.label}</Text></Pressable>)}</ScrollView>
    {overlay && <View style={styles.environment}><Text style={styles.environmentTitle}>{filters.find((f) => f.value === active)?.label}</Text><Text style={styles.environmentText}>{overlay}</Text><Text style={styles.environmentSource}>공공데이터 API · 좌표 미검증 값은 지도 마커로 표시하지 않음</Text></View>}
    <Pressable accessibilityLabel="현재 위치" onPress={() => void location.locate()} style={styles.locate}><LocateFixed size={20} color={location.status === 'granted' ? colors.primary : colors.text} /></Pressable>
    {location.status === 'denied' && <Text style={styles.locationMessage}>위치 권한이 거절되었습니다. 설정에서 허용할 수 있습니다.</Text>}{location.address && <Text style={styles.address}>{location.address}</Text>}
    {selected && <View style={styles.popup}><View style={styles.popupHeader}><Text style={styles.popupTitle}>{selected.userName ?? selected.label}</Text><Pressable onPress={() => setSelected(undefined)}><X size={17} color={colors.muted} /></Pressable></View><Text style={styles.popupStatus}>{selected.status.toUpperCase()} · {selected.source === 'sample' ? '샘플 데이터' : '실데이터'}</Text><Text style={styles.popupText}>장치 {selected.deviceCode ?? '연결 정보 없음'} · 사용자 코드 {selected.userCode ?? '-'}</Text><Text style={styles.popupText}>최근 통신 {selected.lastCommunication ?? '-'} · 배터리 {selected.batteryPercent === undefined ? '-' : `${selected.batteryPercent}%`}</Text><Text style={styles.popupText}>{selected.latitude.toFixed(5)}, {selected.longitude.toFixed(5)}</Text></View>}
  </View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#DCEEF5' }, search: { position: 'absolute', top: 12, left: 12, right: 12, height: 42, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: '#DBDFE8', flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13 }, input: { flex: 1, fontSize: 11, color: colors.text, paddingVertical: 0 }, filters: { position: 'absolute', top: 60, left: 12, right: 0, maxHeight: 42 }, filterContent: { gap: 7, paddingRight: 20 }, chip: { height: 34, paddingHorizontal: 12, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: '#DBDFE8', alignItems: 'center', justifyContent: 'center' }, activeChip: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { fontSize: 11, fontWeight: '700', color: '#606776' }, activeChipText: { color: '#fff' }, results: { position: 'absolute', top: 58, left: 12, right: 12, zIndex: 10, backgroundColor: '#fff', borderRadius: 12, padding: 6, elevation: 8 }, result: { padding: 9, borderBottomWidth: 1, borderBottomColor: colors.line }, resultTitle: { fontSize: 12, fontWeight: '800', color: colors.text }, resultMeta: { fontSize: 9, color: colors.muted, marginTop: 2 }, environment: { position: 'absolute', top: 108, left: 12, right: 12, backgroundColor: 'rgba(255,255,255,.96)', borderRadius: 12, padding: 11 }, environmentTitle: { fontSize: 10, fontWeight: '900', color: colors.primary }, environmentText: { fontSize: 13, fontWeight: '800', color: colors.text, marginTop: 3 }, environmentSource: { fontSize: 8, color: colors.muted, marginTop: 4 }, locate: { position: 'absolute', right: 14, bottom: 150, width: 44, height: 44, borderRadius: 22, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', elevation: 5 }, popup: { position: 'absolute', left: 12, right: 12, bottom: 20, padding: 14, borderRadius: 14, backgroundColor: '#fff', elevation: 7 }, popupHeader: { flexDirection: 'row', justifyContent: 'space-between' }, popupTitle: { fontSize: 15, fontWeight: '900', color: colors.text }, popupStatus: { fontSize: 10, color: colors.primary, fontWeight: '800', marginVertical: 5 }, popupText: { fontSize: 10, color: colors.muted, marginTop: 2 }, locationMessage: { position: 'absolute', bottom: 84, left: 12, backgroundColor: '#fff', padding: 8, borderRadius: 8, fontSize: 9, color: colors.danger }, address: { position: 'absolute', bottom: 84, left: 12, backgroundColor: '#fff', padding: 8, borderRadius: 8, fontSize: 9, color: colors.text } });
