import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View, Pressable } from 'react-native';
import { Search } from 'lucide-react-native';
import { KakaoMapView } from '@/components/kakao-map-view';
import { colors } from '@/constants/theme';
import type { EnvironmentLayer, MapMarker } from '@/types/domain';
const filters = [{ label: '통합', value: 'all' }, { label: '해녀', value: 'haenyeo' }, { label: '태왁', value: 'taewak' }, { label: '위험구역', value: 'danger-zone' }, { label: '풍향·풍속', value: 'wind' }, { label: '수온', value: 'water-temperature' }, { label: '유향·유속', value: 'current' }, { label: '기온', value: 'air-temperature' }, { label: '파고·파주기', value: 'wave' }, { label: '조석', value: 'tide' }] as const;
const markers: MapMarker[] = [{ id: 'h1', subject: 'haenyeo', status: 'safe', latitude: 33.24, longitude: 126.56, label: '고미자' }, { id: 'h2', subject: 'haenyeo', status: 'safe', latitude: 33.45, longitude: 126.91, label: '강춘심' }, { id: 't1', subject: 'taewak', status: 'warning', latitude: 33.23, longitude: 126.63, label: 'TW-102' }, { id: 't2', subject: 'taewak', status: 'danger', latitude: 33.21, longitude: 126.93, label: 'TW-211' }];
export default function HomeScreen() { const [active, setActive] = useState<(typeof filters)[number]['value']>('all'); return <View style={styles.container}><KakaoMapView markers={markers} activeLayer={active as EnvironmentLayer | 'haenyeo' | 'taewak'} /><View style={styles.search}><Search size={15} color={colors.muted} /><TextInput style={styles.input} placeholder="해녀 이름, 태왁 ID, 지역을 검색하세요" placeholderTextColor="#9DA3AF" /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.filters} contentContainerStyle={styles.filterContent}>{filters.map((filter) => <Pressable key={filter.value} onPress={() => setActive(filter.value)} style={[styles.chip, active === filter.value && styles.activeChip]}><Text style={[styles.chipText, active === filter.value && styles.activeChipText]}>{filter.label}</Text></Pressable>)}</ScrollView></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#DCEEF5' }, search: { position: 'absolute', top: 12, left: 12, right: 12, height: 40, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.97)', borderWidth: 1, borderColor: '#DBDFE8', flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13 }, input: { flex: 1, fontSize: 11, fontWeight: '600', color: colors.text, paddingVertical: 0 }, filters: { position: 'absolute', top: 58, left: 12, right: 0, maxHeight: 42 }, filterContent: { gap: 7, paddingRight: 20 }, chip: { height: 34, paddingHorizontal: 12, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.97)', borderWidth: 1, borderColor: '#DBDFE8', alignItems: 'center', justifyContent: 'center' }, activeChip: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { fontSize: 11, fontWeight: '700', color: '#606776' }, activeChipText: { color: 'white' } });
