import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Activity, Clock3, Gauge, MoveDiagonal } from 'lucide-react-native';
import { PageTitle, Screen } from '@/components/screen';
import { Card, SegmentedControl } from '@/components/ui';
import { RiskDonut } from '@/components/risk-donut';
import { colors } from '@/constants/theme';
import { sampleSafetyReports } from '@/data/report-data';
import type { ReportPeriod } from '@/types/domain';
const periods = [{ value: 'daily', label: '일간' }, { value: 'weekly', label: '주간' }, { value: 'monthly', label: '월간' }] as const;
const activityMeta = [{ key: 'workDuration', label: '작업 시간', icon: Clock3 }, { key: 'travelDistance', label: '이동 거리', icon: MoveDiagonal }, { key: 'averageDepth', label: '평균 수심', icon: Activity }, { key: 'highestRisk', label: '최고 위험도', icon: Gauge }] as const;
export default function ReportScreen() { const [period, setPeriod] = useState<ReportPeriod>('daily'); const report = sampleSafetyReports[period]; const legend = [{ label: '안전', value: report.risk.safe, color: '#54BD7A' }, { label: '주의', value: report.risk.caution, color: colors.warning }, { label: '경고', value: report.risk.warning, color: '#F15B5B' }, { label: '위험', value: report.risk.danger, color: '#7B7F8B' }]; return <Screen><PageTitle>AI 리포트</PageTitle><SegmentedControl options={periods} value={period} onChange={setPeriod} blue /><ReportCard title="위험도 종합 분석"><View style={styles.risk}><RiskDonut risk={report.risk} /><View style={styles.legend}>{legend.map((item) => <View key={item.label} style={styles.legendRow}><View style={[styles.dot, { backgroundColor: item.color }]} /><Text style={styles.legendLabel}>{item.label}</Text><Text style={styles.legendValue}>{item.value}%</Text></View>)}</View></View></ReportCard><ReportCard title="주요 활동 요약"><View style={styles.grid}>{activityMeta.map(({ key, label, icon: Icon }) => <View key={key} style={styles.activity}><View style={styles.activityIcon}><Icon size={16} color="#3B7BF3" /></View><View><Text style={styles.activityLabel}>{label}</Text><Text style={styles.activityValue}>{report.activity[key]}</Text></View></View>)}</View></ReportCard><ReportCard title="AI 분석 코멘트"><View style={styles.comment}><Text style={styles.commentTitle}>{report.commentTitle}</Text><Text style={styles.commentText}>{report.comment}</Text></View></ReportCard><ReportCard title="맞춤형 안전 가이드"><View style={styles.guides}>{report.guides.map((guide, index) => <View key={guide.id} style={styles.guide}><View style={styles.num}><Text style={styles.numText}>{index + 1}</Text></View><Text style={styles.guideText}>{guide.text}</Text></View>)}</View></ReportCard></Screen>; }
function ReportCard({ title, children }: React.PropsWithChildren<{ title: string }>) { return <Card style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</Card>; }
const styles = StyleSheet.create({ card: { padding: 14, marginTop: 12 }, cardTitle: { fontSize: 12, fontWeight: '900', color: colors.text, marginBottom: 11 }, risk: { flexDirection: 'row', alignItems: 'center', gap: 16 }, legend: { flex: 1, gap: 7 }, legendRow: { flexDirection: 'row', alignItems: 'center' }, dot: { width: 7, height: 7, borderRadius: 4, marginRight: 6 }, legendLabel: { fontSize: 10, color: colors.text }, legendValue: { marginLeft: 'auto', fontSize: 10, fontWeight: '800' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, activity: { width: '48.6%', minHeight: 64, borderWidth: 1, borderColor: '#EEF0F4', borderRadius: 12, backgroundColor: '#FAFAFC', padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, activityIcon: { width: 30, height: 30, borderRadius: 9, backgroundColor: '#EEF5FF', alignItems: 'center', justifyContent: 'center' }, activityLabel: { fontSize: 9, color: colors.muted, marginBottom: 2 }, activityValue: { fontSize: 11, fontWeight: '800', color: colors.text }, comment: { backgroundColor: '#F8F9FC', borderRadius: 12, padding: 11 }, commentTitle: { fontSize: 10, fontWeight: '800', color: '#282E39', marginBottom: 5 }, commentText: { fontSize: 10, lineHeight: 16, color: '#535A67' }, guides: { gap: 7 }, guide: { borderRadius: 11, backgroundColor: '#F8F9FC', padding: 9, flexDirection: 'row', gap: 8 }, num: { width: 19, height: 19, borderRadius: 10, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, numText: { fontSize: 9, fontWeight: '900', color: colors.primary }, guideText: { flex: 1, fontSize: 10, lineHeight: 15, color: colors.text } });
