import { StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { Activity, BellRing, Clock3, Gauge, MoveDiagonal, Navigation } from 'lucide-react-native';
import { PageTitle, Screen } from '@/components/screen'; import { Card, ErrorState, LoadingState, SegmentedControl } from '@/components/ui'; import { RiskDonut } from '@/components/risk-donut'; import { colors } from '@/constants/theme'; import { safetyReportService } from '@/services/safety-report-service'; import type { ReportPeriod } from '@/types/domain'; import { useState } from 'react';
const periods = [{ value: 'daily', label: '일간' }, { value: 'weekly', label: '주간' }, { value: 'monthly', label: '월간' }] as const;
const activityMeta = [{ key: 'workDuration', label: '작업 시간', icon: Clock3 }, { key: 'travelDistance', label: '이동 거리', icon: MoveDiagonal }, { key: 'averageDepth', label: '평균 수심', icon: Activity }, { key: 'highestRisk', label: '최고 위험도', icon: Gauge }, { key: 'averageRisk', label: '평균 위험도', icon: Gauge }, { key: 'alertCount', label: '알림 건수', icon: BellRing }, { key: 'locationActivity', label: '위치 활동량', icon: Navigation }] as const;
export default function ReportScreen() { const [period, setPeriod] = useState<ReportPeriod>('daily'); const query = useQuery({ queryKey: ['safety-report', period], queryFn: () => safetyReportService.getSafetyReport(period) }); return <Screen><PageTitle>AI 리포트</PageTitle><SegmentedControl options={periods} value={period} onChange={setPeriod} blue />{query.isLoading ? <LoadingState label="실제 안전 데이터를 집계하는 중..." /> : query.error ? <ErrorState message={query.error.message} action="다시 시도" onRetry={() => void query.refetch()} /> : query.data && <Report report={query.data} />}</Screen>; }
function Report({ report }: { report: Awaited<ReturnType<typeof safetyReportService.getSafetyReport>> }) { const legend = [{ label: '안전', value: report.risk.safe, color: '#54BD7A' }, { label: '주의', value: report.risk.caution, color: colors.warning }, { label: '경고', value: report.risk.warning, color: '#F15B5B' }, { label: '위험', value: report.risk.danger, color: '#7B7F8B' }]; return <><ReportCard title="위험도 종합 분석"><View style={styles.risk}><RiskDonut risk={report.risk} /><View style={styles.legend}>{legend.map((item) => <View key={item.label} style={styles.legendRow}><View style={[styles.dot, { backgroundColor: item.color }]} /><Text style={styles.legendLabel}>{item.label}</Text><Text style={styles.legendValue}>{item.value}%</Text></View>)}</View></View></ReportCard><ReportCard title="주요 활동 요약"><View style={styles.grid}>{activityMeta.map(({ key, label, icon: Icon }) => <View key={key} style={styles.activity}><Icon size={15} color="#3B7BF3" /><View><Text style={styles.activityLabel}>{label}</Text><Text style={styles.activityValue}>{report.activity[key]}</Text></View></View>)}</View></ReportCard><ReportCard title="규칙 기반 안전 분석"><View style={styles.comment}><Text style={styles.commentTitle}>{report.commentTitle}</Text><Text style={styles.commentText}>{report.comment}</Text></View></ReportCard><ReportCard title="맞춤형 안전 가이드">{report.guides.length ? <View style={styles.guides}>{report.guides.map((guide, index) => <View key={guide.id} style={styles.guide}><Text style={styles.num}>{index + 1}</Text><View style={{ flex: 1 }}><Text style={styles.guideText}>{guide.text}</Text><Text style={styles.source}>{guide.reference}</Text></View></View>)}</View> : <Text style={styles.empty}>현재 데이터에서 추가 안전 가이드가 생성되지 않았습니다.</Text>}</ReportCard></>; }
function ReportCard({ title, children }: React.PropsWithChildren<{ title: string }>) { return <Card style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</Card>; }
const styles = StyleSheet.create({ card: { padding: 14, marginTop: 12 }, cardTitle: { fontSize: 12, fontWeight: '900', color: colors.text, marginBottom: 11 }, risk: { flexDirection: 'row', alignItems: 'center', gap: 16 }, legend: { flex: 1, gap: 7 }, legendRow: { flexDirection: 'row', alignItems: 'center' }, dot: { width: 7, height: 7, borderRadius: 4, marginRight: 6 }, legendLabel: { fontSize: 10, color: colors.text }, legendValue: { marginLeft: 'auto', fontSize: 10, fontWeight: '800' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, activity: { width: '48.5%', minHeight: 57, borderWidth: 1, borderColor: '#EEF0F4', borderRadius: 12, backgroundColor: '#FAFAFC', padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, activityLabel: { fontSize: 9, color: colors.muted }, activityValue: { fontSize: 11, fontWeight: '800', color: colors.text }, comment: { backgroundColor: '#F8F9FC', borderRadius: 12, padding: 11 }, commentTitle: { fontSize: 10, fontWeight: '800', color: '#282E39', marginBottom: 5 }, commentText: { fontSize: 10, lineHeight: 16, color: '#535A67' }, guides: { gap: 7 }, guide: { borderRadius: 11, backgroundColor: '#F8F9FC', padding: 9, flexDirection: 'row', gap: 8 }, num: { width: 19, height: 19, borderRadius: 10, backgroundColor: colors.primarySoft, textAlign: 'center', color: colors.primary, fontWeight: '900' }, guideText: { fontSize: 10, lineHeight: 15, color: colors.text }, source: { fontSize: 8, color: colors.muted, marginTop: 3 }, empty: { fontSize: 10, color: colors.muted } });
