import { useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import * as Location from 'expo-location';
import * as ImagePicker from 'expo-image-picker';
import { ImagePlus, LocateFixed, MapPin, Trash2 } from 'lucide-react-native';
import { Screen } from '@/components/screen';
import { EmptyState, SegmentedControl } from '@/components/ui';
import { colors } from '@/constants/theme';
type SosTab = 'write' | 'history';
export default function SosScreen() {
  const [tab, setTab] = useState<SosTab>('write'); const [description, setDescription] = useState(''); const [consent, setConsent] = useState(true); const [address, setAddress] = useState('위치를 확인하려면 눌러주세요'); const [coords, setCoords] = useState<{ latitude: number; longitude: number } | null>(null); const [asset, setAsset] = useState<ImagePicker.ImagePickerAsset | null>(null); const [locating, setLocating] = useState(false);
  const locate = async () => { setLocating(true); try { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) { setAddress('위치 권한이 필요합니다'); return; } const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setCoords(position.coords); const places = await Location.reverseGeocodeAsync(position.coords); const place = places[0]; setAddress(place ? [place.region, place.city, place.district, place.street].filter(Boolean).join(' ') : `${position.coords.latitude.toFixed(5)}, ${position.coords.longitude.toFixed(5)}`); } catch { setAddress('위치를 확인하지 못했습니다'); } finally { setLocating(false); } };
  const pickMedia = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images', 'videos'], allowsEditing: false, quality: 0.8 }); if (!result.canceled) setAsset(result.assets[0] ?? null); };
  const submit = () => { if (!consent) return Alert.alert('공유 동의 필요', '위치 정보 및 사진 공유에 동의해 주세요.'); Alert.alert('신고 준비 완료', `현재 단계에서는 실제 구조기관이나 DB로 전송하지 않습니다.${coords ? '' : '\n위치 정보가 아직 없습니다.'}`); };
  return <Screen><SegmentedControl options={[{ value: 'write', label: '신고하기' }, { value: 'history', label: '신고 내역' }]} value={tab} onChange={setTab} />{tab === 'history' ? <EmptyState title="신고 내역이 없습니다" description="신고 저장소 연결 후 이곳에서 처리 상태를 확인할 수 있어요." /> : <><View style={styles.sos}><View style={styles.circle}><Text style={styles.sosText}>SOS</Text></View><Text style={styles.sosTitle}>긴급 구조 요청</Text><Text style={styles.sosSub}>위험한 상황을 빠르게 공유하고 구조를 요청하세요.</Text></View><Text style={styles.label}>위치 정보</Text><Pressable onPress={locate} style={styles.location}><View style={styles.locationBadge}><MapPin size={13} color={colors.primary} /><Text style={styles.locationBadgeText}>제주특별자치도</Text></View><Text numberOfLines={1} style={styles.address}>{locating ? '현재 위치 확인 중...' : address}</Text><LocateFixed size={17} color={colors.muted} /></Pressable><Text style={styles.label}>상황 설명 (선택)</Text><TextInput multiline value={description} onChangeText={setDescription} placeholder="현재 상황을 입력해 주세요." placeholderTextColor="#A6ABB5" textAlignVertical="top" style={styles.textarea} /><Text style={styles.label}>사진/영상 첨부 (선택)</Text><View style={styles.attachRow}><Pressable onPress={pickMedia} style={styles.add}><ImagePlus size={23} color={colors.muted} /><Text style={styles.addText}>추가</Text></Pressable>{asset && <View style={styles.preview}><Image source={{ uri: asset.uri }} style={styles.thumbnail} /><Pressable onPress={() => setAsset(null)} style={styles.remove}><Trash2 size={13} color="white" /></Pressable>{asset.type === 'video' && <Text style={styles.video}>VIDEO</Text>}</View>}</View><View style={styles.consent}><Switch value={consent} onValueChange={setConsent} trackColor={{ false: '#D8DCE4', true: colors.primary }} thumbColor="white" style={styles.smallSwitch} /><Text style={styles.consentText}>위치 정보 및 사진 공유 동의</Text><Pressable onPress={() => Alert.alert('공유 동의', '긴급 신고 처리를 위해 현재 위치와 첨부 미디어를 신고 처리 담당자에게 공유합니다.')} style={styles.detail}><Text style={styles.detailText}>내용보기</Text></Pressable></View><Pressable onPress={submit} style={styles.submit}><Text style={styles.submitText}>신고하기</Text></Pressable></>}</Screen>;
}
const styles = StyleSheet.create({ sos: { marginTop: 14, borderWidth: 2, borderColor: '#F73A3A', backgroundColor: '#EF2727', borderRadius: 14, padding: 20, alignItems: 'center' }, circle: { width: 68, height: 68, borderRadius: 34, backgroundColor: 'white', alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, sosText: { color: '#E52828', fontWeight: '900', fontSize: 20 }, sosTitle: { color: 'white', fontSize: 16, fontWeight: '900', marginBottom: 4 }, sosSub: { color: 'white', opacity: 0.9, fontSize: 10 }, label: { fontSize: 12, fontWeight: '800', color: colors.text, marginTop: 16, marginHorizontal: 2, marginBottom: 7 }, location: { minHeight: 46, backgroundColor: 'white', borderWidth: 1, borderColor: '#E7E9F0', borderRadius: 12, paddingHorizontal: 12, flexDirection: 'row', gap: 10, alignItems: 'center' }, locationBadge: { height: 28, borderRadius: 9, backgroundColor: colors.primarySoft, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 5 }, locationBadgeText: { color: colors.primary, fontSize: 10, fontWeight: '800' }, address: { flex: 1, color: '#5D6472', fontSize: 11, fontWeight: '700' }, textarea: { height: 92, borderWidth: 1, borderColor: '#E4E7ED', borderRadius: 12, backgroundColor: 'white', padding: 12, fontSize: 11, color: colors.text }, attachRow: { flexDirection: 'row', gap: 8 }, add: { width: 74, height: 74, borderRadius: 12, borderWidth: 1, borderStyle: 'dashed', borderColor: '#C9CDD7', backgroundColor: 'white', alignItems: 'center', justifyContent: 'center', gap: 4 }, addText: { color: colors.muted, fontSize: 9 }, preview: { width: 74, height: 74, borderRadius: 12, overflow: 'hidden' }, thumbnail: { width: '100%', height: '100%' }, remove: { position: 'absolute', top: 4, right: 4, width: 22, height: 22, borderRadius: 11, backgroundColor: 'rgba(0,0,0,0.58)', alignItems: 'center', justifyContent: 'center' }, video: { position: 'absolute', bottom: 4, left: 4, fontSize: 8, color: 'white', backgroundColor: '#0008', padding: 2 }, consent: { flexDirection: 'row', alignItems: 'center', marginTop: 15, marginBottom: 12, padding: 10, borderRadius: 12, backgroundColor: '#F4F1FF' }, smallSwitch: { transform: [{ scale: 0.7 }], marginLeft: -7 }, consentText: { fontSize: 10, color: '#616876', flex: 1 }, detail: { borderWidth: 1, borderColor: '#DDD8F3', borderRadius: 10, paddingVertical: 6, paddingHorizontal: 10 }, detailText: { fontSize: 10, fontWeight: '800', color: '#6E61A8' }, submit: { height: 48, backgroundColor: '#ED2929', borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, submitText: { color: 'white', fontSize: 13, fontWeight: '900' } });
