import { AlertTriangle, UserRound, WifiOff } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/constants/theme';
import type { EnvironmentLayer, MapCamera, MapMarker, RiskZone } from '@/types/domain';
export interface KakaoMapViewProps { markers: MapMarker[]; activeLayer: EnvironmentLayer; camera?: MapCamera; riskZones?: RiskZone[]; onMarkerPress?: (marker: MapMarker) => void; onMapReady?: () => void }
const positions = [{ left: '20%', top: '48%' }, { right: '14%', top: '39%' }, { left: '52%', top: '57%' }, { right: '8%', top: '62%' }] as const;
export function FallbackMap({ markers, onMarkerPress }: KakaoMapViewProps) {
  return <View style={styles.map}><View style={styles.island} /><Text style={styles.notice}>Kakao Map 미연결 · 대체 지도</Text><Text style={[styles.label, { left: '41%', top: '45%' }]}>제주시</Text><Text style={[styles.label, { left: '38%', top: '59%' }]}>서귀포</Text>
    {markers.map((marker, index) => <Pressable accessibilityLabel={`${marker.label} ${marker.status}`} onPress={() => onMarkerPress?.(marker)} key={marker.id} style={[styles.marker, positions[index % positions.length], { backgroundColor: marker.status === 'safe' ? colors.safe : marker.status === 'caution' || marker.status === 'warning' ? colors.warning : marker.status === 'danger' ? colors.danger : colors.disconnected }]}>{marker.status === 'disconnected' ? <WifiOff size={15} color="white" /> : marker.kind === 'user' ? <UserRound size={16} color="white" /> : <AlertTriangle size={16} color="white" />}</Pressable>)}
    <Text style={styles.source}>실시간 관제</Text></View>;
}
const styles = StyleSheet.create({ map: { ...StyleSheet.absoluteFillObject, overflow: 'hidden', backgroundColor: '#DCEEF5' }, island: { position: 'absolute', width: '82%', height: '31%', left: '11%', top: '34%', borderRadius: 120, backgroundColor: '#F5F1D8', borderWidth: 8, borderColor: 'white', transform: [{ rotate: '-5deg' }] }, label: { position: 'absolute', color: '#707A82', fontSize: 12, fontWeight: '800' }, notice: { position: 'absolute', alignSelf: 'center', top: '30%', backgroundColor: '#fff', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 9, color: colors.muted, fontSize: 10, fontWeight: '800' }, marker: { position: 'absolute', width: 36, height: 36, borderRadius: 18, borderWidth: 3, borderColor: 'white', alignItems: 'center', justifyContent: 'center', elevation: 4 }, source: { position: 'absolute', right: 10, bottom: 12, fontSize: 9, color: colors.muted, backgroundColor: '#fff', padding: 5, borderRadius: 6 } });
