import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type StyleProp, type ViewStyle } from 'react-native';
import { Search } from 'lucide-react-native';
import { colors, radius, spacing, typography } from '@/constants/theme';

export function Card({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function SectionHeader({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{action && <Pressable onPress={onAction}><Text style={styles.action}>{action}</Text></Pressable>}</View>; }
export function SearchBar({ placeholder, value, onChangeText }: { placeholder: string; value?: string; onChangeText?: (text: string) => void }) { return <View style={styles.search}><Search size={16} color={colors.muted} /><TextInput placeholder={placeholder} placeholderTextColor="#A2A7B3" value={value} onChangeText={onChangeText} style={styles.searchInput} /></View>; }
export function StatusBadge({ label, tone = 'safe' }: { label: string; tone?: 'safe' | 'warning' | 'danger' | 'neutral' }) { const bg = tone === 'safe' ? '#E8F8F0' : tone === 'warning' ? '#FFF5DF' : tone === 'danger' ? '#FDEAEA' : colors.soft; return <View style={[styles.badge, { backgroundColor: bg }]}><Text style={styles.badgeText}>{label}</Text></View>; }
export function EmptyState({ title, description }: { title: string; description?: string }) { return <View style={styles.state}><Text style={styles.stateTitle}>{title}</Text>{description && <Text style={styles.stateText}>{description}</Text>}</View>; }
export function LoadingState({ label = '불러오는 중...' }: { label?: string }) { return <View style={styles.state}><ActivityIndicator color={colors.primary} /><Text style={styles.stateText}>{label}</Text></View>; }
export function ErrorState({ message, action, onRetry }: { message: string; action?: string; onRetry?: () => void }) { return <View style={styles.state}><Text style={styles.stateTitle}>잠시 문제가 생겼어요</Text><Text style={styles.stateText}>{message}</Text>{action && <Pressable onPress={onRetry}><Text style={styles.action}>{action}</Text></Pressable>}</View>; }
export function SegmentedControl<T extends string>({ options, value, onChange, blue = false }: { options: readonly { value: T; label: string }[]; value: T; onChange: (value: T) => void; blue?: boolean }) { return <View style={styles.segment}>{options.map((option) => <Pressable key={option.value} onPress={() => onChange(option.value)} style={[styles.segmentItem, option.value === value && styles.segmentActive, option.value === value && blue && styles.segmentBlue]}><Text style={[styles.segmentText, option.value === value && styles.segmentActiveText, option.value === value && blue && styles.segmentBlueText]}>{option.label}</Text></Pressable>)}</View>; }
export function IconCircle({ children }: { children: ReactNode }) { return <View style={styles.iconCircle}>{children}</View>; }

const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg }, section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.lg, marginBottom: 9 }, sectionTitle: { fontSize: 13, fontWeight: '900', color: colors.text }, action: { fontSize: 10, fontWeight: '800', color: colors.primary }, search: { height: 46, borderRadius: radius.md, backgroundColor: colors.soft, borderWidth: 1, borderColor: '#ECEEF3', flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 13 }, searchInput: { flex: 1, color: colors.text, fontSize: typography.small, paddingVertical: 0 }, badge: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: radius.pill }, badgeText: { fontSize: 10, fontWeight: '800', color: colors.text }, state: { padding: 24, alignItems: 'center', gap: 8 }, stateTitle: { fontSize: 14, fontWeight: '800', color: colors.text }, stateText: { fontSize: 11, color: colors.muted, textAlign: 'center' }, segment: { height: 38, backgroundColor: '#EFF1F5', borderRadius: 10, flexDirection: 'row', padding: 3 }, segmentItem: { flex: 1, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, segmentActive: { backgroundColor: colors.surface }, segmentBlue: { backgroundColor: colors.blue }, segmentText: { fontSize: 12, fontWeight: '800', color: colors.muted }, segmentActiveText: { color: colors.blue }, segmentBlueText: { color: colors.surface }, iconCircle: { width: 32, height: 32, borderRadius: 9, backgroundColor: '#F4F1FF', alignItems: 'center', justifyContent: 'center' } });
