import type { PublicDataResult, PublicDataService, NormalizedPublicDataRecord } from '@/types/public-data';
import type { RiskInput } from '@/lib/risk/risk-engine';

export type PublicDataSnapshot = Partial<Record<PublicDataService, PublicDataResult>>;
export interface EnvironmentField { key: string; label: string; value: string; status: 'success' | 'no_data' | 'error'; sources: PublicDataService[] }
export interface MarineSafetySnapshot { fields: EnvironmentField[]; riskInput: RiskInput }
const records = (result?: PublicDataResult) => result?.status === 'success' ? result.data.items : [];
const latest = (rows: NormalizedPublicDataRecord[]) => [...rows].sort((a, b) => Date.parse(b.observedAt ?? b.forecastAt ?? '') - Date.parse(a.observedAt ?? a.forecastAt ?? ''))[0];
const raw = (row: NormalizedPublicDataRecord | undefined, ...keys: string[]) => { for (const key of keys) { const value = row?.values[key] ?? row?.raw[key]; if (value !== null && value !== undefined && value !== '') return value; } return null; };
const num = (value: unknown) => { const n = Number(value); return value === null || value === '' || !Number.isFinite(n) ? null : n; };
const stateValue = (sources: (PublicDataResult | undefined)[], value: string | null): Pick<EnvironmentField, 'value' | 'status'> => sources.some((v) => v?.status === 'error') && value === null ? { value: '정보를 불러오지 못했습니다', status: 'error' } : value === null ? { value: '데이터 없음', status: 'no_data' } : { value, status: 'success' };
const fmt = (n: number | null, unit: string, digits = 1) => n === null ? null : `${n.toFixed(digits)} ${unit}`;

export function adaptSafetyPublicData(snapshot: PublicDataSnapshot, now = new Date()): MarineSafetySnapshot {
  const alert = latest(records(snapshot['weather-alert'])); const forecastRows = records(snapshot['short-term-forecast']); const wave = latest(records(snapshot['wave-observation'])); const current = latest(records(snapshot['tidal-current'])); const tide = latest(records(snapshot['tidal-observation'])); const tides = records(snapshot['tide-forecast']); const buoy = latest(records(snapshot['ocean-buoy'])); const marine = latest(records(snapshot['marine-forecast']));
  const forecast = (category: string) => latest(forecastRows.filter((row) => row.values.category === category));
  const wind = num(raw(buoy ?? tide, 'windSpeed', 'wspd')) ?? num(raw(forecast('WSD'), 'value')); const waveHeight = num(raw(wave ?? buoy, 'waveHeight', 'wvhgt')); const wavePeriod = num(raw(wave ?? buoy, 'wavePeriod', 'wvpd')); const water = num(raw(tide ?? buoy, 'waterTemperature', 'wtem')); const direction = num(raw(current, 'currentDirection', 'crdir')); const speed = num(raw(current, 'currentSpeed', 'crsp'));
  const alertTitle = raw(alert, 'title'); const pcpRaw = raw(forecast('PCP'), 'value'); const pcp = pcpRaw === null ? null : /없음/.test(String(pcpRaw)) ? 0 : num(String(pcpRaw).match(/[0-9.]+/)?.[0]); const pop = num(raw(forecast('POP'), 'value'));
  const futureTide = tides.filter((row) => Date.parse(row.forecastAt ?? '') >= now.getTime()).sort((a, b) => Date.parse(a.forecastAt ?? '') - Date.parse(b.forecastAt ?? ''))[0] ?? tides[0]; const tideType = String(raw(futureTide, 'tideType', 'extrSe') ?? '조석'); const tideText = futureTide?.forecastAt ? `${tideType} ${new Intl.DateTimeFormat('ko-KR', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(futureTide.forecastAt))}` : null;
  const values: [string,string,string | null,(PublicDataResult | undefined)[]][] = [
    ['weatherAlert','기상특보',alertTitle === null ? null : String(alertTitle),[snapshot['weather-alert']]], ['wind','풍속',fmt(wind,'m/s'),[snapshot['ocean-buoy'],snapshot['short-term-forecast']]], ['precipitation','단기예보 강수',pcp === null ? (pop === null ? null : `강수확률 ${pop.toFixed(0)}%`) : `${pcp.toFixed(1)} mm${pop === null ? '' : ` · ${pop.toFixed(0)}%`}`,[snapshot['short-term-forecast']]], ['wave','파고·파주기',waveHeight === null && wavePeriod === null ? null : `${fmt(waveHeight,'m') ?? '데이터 없음'} · ${fmt(wavePeriod,'s') ?? '데이터 없음'}`,[snapshot['wave-observation'],snapshot['ocean-buoy']]], ['waterTemperature','수온',fmt(water,'℃'),[snapshot['tidal-observation'],snapshot['ocean-buoy']]], ['current','유향·유속',direction === null || speed === null ? null : `${direction.toFixed(0)}° · ${speed.toFixed(1)} cm/s`,[snapshot['tidal-current']]], ['nextTide','다음 조석',tideText,[snapshot['tide-forecast']]], ['marineForecast','해상예보',raw(marine,'text','wf') === null ? null : String(raw(marine,'text','wf')),[snapshot['marine-forecast']]],
  ];
  const weatherAlert = /풍랑경보/.test(String(alertTitle)) ? 'wave_warning' : /풍랑주의보/.test(String(alertTitle)) ? 'wave_advisory' : 'none';
  const serviceSources: Record<string, PublicDataService[]> = { weatherAlert: ['weather-alert'], wind: ['ocean-buoy', 'short-term-forecast'], precipitation: ['short-term-forecast'], wave: ['wave-observation', 'ocean-buoy'], waterTemperature: ['tidal-observation', 'ocean-buoy'], current: ['tidal-current'], nextTide: ['tide-forecast'], marineForecast: ['marine-forecast'] };
  return { fields: values.map(([key,label,value,sources]) => ({ key, label, ...stateValue(sources, value), sources: serviceSources[key] ?? [] })), riskInput: { assessedAt: now.toISOString(), weatherAlert, windSpeedMps: wind, waveHeightM: waveHeight, currentSpeedCms: speed, waterTemperatureC: water, precipitationMm: pcp, precipitationProbability: pop } };
}
